BEGIN TRANSACTION;
DROP TABLE IF EXISTS "external_funds";
CREATE TABLE IF NOT EXISTS "external_funds" (
	"FUND_NAME" TEXT,
	"REPORT_DATE" TEXT,
	"FINANCIAL TYPE" TEXT,
	"SYMBOL" TEXT,
	"SECURITY NAME" TEXT,
	"ISIN" TEXT,
	"PRICE" TEXT,
	"QUANTITY" TEXT,
	"REALISED P/L" TEXT,
	"MARKET VALUE" TEXT
);
COMMIT;
