name: dbt_gic_takehome

config-version: 2
version: 1.0

profile: dbt_postgres

model-paths: ["models"]

clean-targets:
  - target
  - dbt_packages

models:
  dbt_gic_takehome:
    +materialized: table

    core:
      +schema: core
      +docs: 
        node_color: blue

    marts:
      +schema: marts
      +docs: 
        node_color: gold

    staging:
      +schema: staging
      +docs: 
        node_color: red
